export default [
  { type: 'stand1', text: 'action_standing_1_handed' },
  { type: 'stand2', text: 'action_standing_2_handed' },
  { type: 'walk1', text: 'action_walking_1_handed' },
  { type: 'walk2', text: 'action_walking_2_handed' },
  { type: 'alert', text: 'action_alert' },
  { type: 'fly', text: 'action_flying' },
  { type: 'heal', text: 'action_healing' },
  { type: 'jump', text: 'action_jumping' },
  { type: 'ladder', text: 'action_ladder' },
  { type: 'rope', text: 'action_rope' },
  { type: 'prone', text: 'action_prone' },
  { type: 'proneStab', text: 'action_prone_stab' },
  { type: 'shoot1', text: 'action_shoot_1_handed' },
  { type: 'shoot2', text: 'action_shoot_2_handed' },
  { type: 'shootF', text: 'action_shoot_0f' },
  { type: 'sit', text: 'action_sitting' },
  /* { type: 'stabO1', text: 'action_stab_01' },
  { type: 'stabO2', text: 'action_stab_02' },
  { type: 'stabOF', text: 'action_stab_0f' },
  { type: 'stabT1', text: 'action_stab_t1' },
  { type: 'stabT2', text: 'action_stab_t2' },
  { type: 'stabTF', text: 'action_stab_tf' },
  { type: 'swingO1', text: 'action_swing_01' },
  { type: 'swingO2', text: 'action_swing_02' },
  { type: 'swingO3', text: 'action_swing_03' },
  { type: 'swingOF', text: 'action_swing_0f' },
  { type: 'swingP1', text: 'action_swing_p1' },
  { type: 'swingP2', text: 'action_swing_p2' },
  { type: 'swingPF', text: 'action_swing_pf' },
  { type: 'swingT1', text: 'action_swing_t1' },
  { type: 'swingT2', text: 'action_swing_t2' },
  { type: 'swingT3', text: 'action_swing_t3' },
  { type: 'swingTF', text: 'action_swing_tf' }, */
]
